inheritance/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from temp_inheritance import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'admin/', admin.site.urls),
    url(r'inheritance/',include('temp_inheritance.urls')),
]

temp_inheritance/urls.py
from django.conf.urls import url
from temp_inheritance import views

app_name='temp_inheritance'
urlpatterns=[
    url(r'^relative/$',views.base,name='base'),
    url(r'^others/$',views.others,name='others'),
]

temp_inheritance/models.py
from django.db import models

# Create your models here.

temp_inheritance/views.py
from django.shortcuts import render
import logging
import time
logging.config.dictConfig({
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            'format': '%(name)-12s %(levelname)-8s %(message)s'
        },
        'file': {
            'format': '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'formatter': 'file',
            'filename': 'test_log.log'
        }
    },
    'loggers': {
        '': {
            'level': 'DEBUG',
            'handlers': ['console', 'file']
        }
    }
})
logger = logging.getLogger('Test-logging')



def my_logger(func1):
    def wrapper(*args,**kwargs):
         logging.info('started running the file')
         return func1(*args,**kwargs)
    return wrapper

def my_timer(func1):
    def wrapper(*args,**kwargs):
              t1=time.time()
              result=func1(*args,**kwargs)
              t2=time.time()-t1
              logging.info("Done running:{}".format(func1.__name__))    
              logging.info('{} ran in{} sec'.format(func1.__name__,t2))
              return result
           


    return wrapper

@my_logger
@my_timer
def index(request):
 return render(request,'temp_inheritance/index.html')

    
@my_logger
@my_timer
def others(request):
    try:
     return render(request,'temp_inheritance/others.html')
    except Exception as eyea:
        logging.exception ("no such templates are found")
@my_logger
@my_timer
def base(request):
    return render(request,'temp_inheritance/base.html')
    

templates/temp_inheritance/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <title>inheritance_testing</title>
</head>
<body>
    <nav class="navbar nav-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{%url 'temp_inheritance:others'%}">BRAND</a></li>
                <li><a class="navbar-link" href="{%url 'admin:index'%}">ADMIN</a></li>
                <li><a class="navbar-link" href="{%url 'index'%}">HOME</a></li>

            </ul>
        </div>
    </nav>
    <div class="container">
        {%block body_block%}

        {%endblock%}
    </div>
</body>
</html>

templates/temp_inheritance/index.html
<!DOCTYPE html>
{%extends "temp_inheritance/base.html"%}
    {%block body_block%}
           <h1>WELCOME TO INDEX</h1>

    {%endblock%}